config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get '/rankings', to: 'posts#rankings'
 
  devise_for :users
  resources :posts, only: [:new, :index, :create, :show, :destroy, :edit, :update]
  resources :posts, only: [:index, :new, :create] do
    resource :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
    { id: 3, name: 'その他' }
  ]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :hobby, presence: true
  validates :required_time, presence: true
  validates :budget, presence: true
  validates :number_of_people, presence: true
  has_many :likes

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :validatable

  validates :nickname, presence: true
  has_many :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :prefecture_id, :gender, :date_of_birth])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    like = current_user.likes.build(post_id: params[:post_id])
    if like.save
      respond_to do |format|
        format.js
      end
    else
      # いいねが正常に保存されなかった場合のエラーハンドリングを行う
      # 例: エラーメッセージを設定し、適切なリダイレクトを行う
      flash[:alert] = 'いいねの作成に失敗しました。'
      redirect_to root_path
    end
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    respond_to do |format|
      format.js
    end
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :rankings]

  def index
    @posts = Post.all
    @users = User.all
  end

  def create
    @post = current_user.posts.build(post_params) # ユーザーとの関連付けを行う
  
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to post_path
  end


  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def rankings
    @rankings = Post.joins(:likes).group(:id).order('COUNT(likes.id) DESC')
  end

  
  private
  def post_params
    params.require(:post).permit(:hobby, :required_time, :budget, :number_of_people)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @posts = Post.all 
  end

  def edit
  end

  def show
    @nickname = current_user.nickname
    @posts = current_user.posts
  end

  def user_params
    params.require(:user).permit(:nickname, :email,)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Next Hobby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Next Hobby</a></h1>
        <div class="user_nav grid-6">
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Next Hobby 2023.
      </p>
    </footer>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? && post.liked_by?(current_user)%>
  <%=link_to "いいね済", post_likes_path(post.id),  data: { turbo_method: :delete }, class: "post_likes" , remote: true %>
<% else %>
  <%=link_to "いいねする", post_likes_path(post.id), data: { turbo_method: :post }, class: "post_likes" , remote: true %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @tweet.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @tweet.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"

app/views/posts/edit.html.erb
<div class="center">
  <div class="container">
   <h3>編集する</h3>
    <%= form_with(model: @post, url: post_path(@post), method: :patch, id: "form") do |form| %>
      <div class="form-group">
        <%= form.label :hobby, "趣味の内容" %>
        <%= form.text_field :hobby %>
      </div>

      <div class="form-group">
        <%= form.label :required_time, "所要時間（分）" %>
        <%= form.number_field :required_time %>
      </div>

      <div class="form-group">
        <%= form.label :budget, "予算" %>
        <%= form.text_field :budget %>
      </div>

      <div class="form-group">
        <%= form.label :number_of_people, "参加人数" %>
        <%= form.number_field :number_of_people %>
      </div>

      <div class="actions">
        <%= form.submit '更新する' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<style>
  /* クラス名やセレクタは必要に応じて調整してください */
  .post-content a {
    text-decoration: none; /* 下線を消すスタイル */
  }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</header>
<main>
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-date">
        <span class="label">投稿日時：</span><%= post.created_at %>
      </div>
      <div class="post-content">
        <%= link_to post.hobby, post_path(post) %> 
      </div>
      <div id="like-btn<%= post.id %>">
        <% if user_signed_in? && post.liked_by?(current_user) %>
          <%= link_to post_likes_path(post.id), data: { turbo_method: :delete }, class: "post_likes" do %>
            <i class="fas fa-heart like-btn" ></i>
          <% end %>
        <% else %>
          <%= link_to post_likes_path(post.id), data: { turbo_method: :post }, class: "post_likes" do %>
            <i class="far fa-heart unlike-btn"></i>
          <% end %>
        <% end %>
        <!-- いいねのカウントを表示 -->
        <%= post.likes.count %> いいね
      </div>
      <% if user_signed_in? && current_user.id == post.user_id %>
  <!-- 不要なドットを削除 -->
  <%= link_to '編集', edit_post_path(post.id), class: 'hobby-btn' %> 
  <%= link_to '削除', post_path(post.id), data: { turbo_method: :delete }, class: 'hobby-btn' %>
<% end %>
    </div>
  <% end %>
</main>
</body>

app/views/posts/new.html.erb
<div class="form-container">
  <div class="form-box">
  <h2>趣味の新規登録</h2>
    <%= form_with(model: @post, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :hobby, "趣味の内容" %>
        <%= form.text_field :hobby %>
      </div>

      <div class="form-group">
        <%= form.label :required_time, "所要時間（分）" %>
        <%= form.number_field :required_time %>
      </div>

      <div class="form-group">
        <%= form.label :budget, "予算" %>
        <%= form.text_field :budget %>
      </div>

      <div class="form-group">
        <%= form.label :number_of_people, "参加人数" %>
        <%= form.number_field :number_of_people %>
      </div>
      
       <div class='actions'>
          <%= form.submit "新規登録", class: 'btn'%>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/rankings.html.erb
<div class="center">
<h1>いいねランキング</h1>
<ul>
  <% @rankings.each_with_index do |post, index| %>
    <li>
      <span><%= index + 1 %>位</span>
      <%= link_to post.hobby, post_path(post) %>
      <span>いいね数: <%= post.likes.count %></span>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<div class="contents row">
  <div class="post">
    <div class="post-date">
      <span class="label">投稿日時：</span><%= @post.created_at %>
    </div>
    <div class="post-content">
      <p>趣味名: <%= @post.hobby %></p>
      <p>所要時間: <%= @post.required_time %> 分</p>
      <p>予算: <%= @post.budget %> 円</p>
      <p>参加人数: <%= @post.number_of_people %></p>
    </div>
     <% if user_signed_in? && current_user.id == @post.user_id %>   
    <ul class="more_list">
        <li>
          <%= link_to '編集', edit_post_path(@post) %>
        </li>
        <li>
          <%= link_to '削除', post_path(@post), data: { turbo_method: :delete }, method: :delete %>
        </li>
         <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NEXT HOBBY</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
  <% if current_user %>
  <div class="header-buttons">
    <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'button' %>
    <%= link_to '趣味登録', new_post_path, class: 'button' %>
    <%= link_to '趣味一覧', posts_path, class: 'button' %> <!-- 趣味一覧ボタンを追加 -->
    <%= link_to 'ランキング', rankings_path, class: 'button' %> <!-- ランキングボタンを追加 -->
  </div>
<% else %>
  <div class="header-buttons">
    <%= link_to '新規登録', new_user_registration_path, class: 'button' %>
    <%= link_to 'ログイン', new_user_session_path, class: 'button' %>
    <%= link_to '趣味一覧', posts_path, class: 'button' %> <!-- 趣味一覧ボタンを追加 -->
    <%= link_to 'ランキング', rankings_path, class: 'button' %> <!-- ランキングボタンを追加 -->
  </div>
<% end %>